export const memberSchema = {
  name: "member",
  title: "MEOVV Member",
  type: "document",
  fields: [
    { name: "name", type: "string", title: "Stage Name" },
    { name: "koreanName", type: "string", title: "Korean / Full Name" },
    {
      name: "slug",
      type: "slug",
      title: "Slug",
      options: { source: "name", maxLength: 96 },
    },
    {
      name: "positions",
      type: "array",
      of: [{ type: "string" }],
      title: "Positions",
    },
    { name: "birthDate", type: "string", title: "Birth Date" },
    { name: "birthplace", type: "string", title: "Birthplace" },
    { name: "zodiac", type: "string", title: "Zodiac Sign" },
    { name: "mbti", type: "string", title: "MBTI" },
    { name: "height", type: "string", title: "Height" },
    { name: "bloodType", type: "string", title: "Blood Type" },
    {
      name: "profilePhoto",
      type: "image",
      title: "Profile Photo (Square)",
      options: { hotspot: true },
    },
    {
      name: "pillarPhoto",
      type: "image",
      title: "Pillar Photo (Vertical Tall Crop)",
      options: { hotspot: true },
    },
    {
      name: "heroPhoto",
      type: "image",
      title: "Hero Close-up Photo",
      options: { hotspot: true },
    },
    { name: "quote", type: "string", title: "Catchphrase / Archetype Quote" },
    {
      name: "bio",
      type: "array",
      of: [{ type: "text" }],
      title: "Biography Paragraphs",
    },
    {
      name: "trivia",
      type: "array",
      of: [{ type: "string" }],
      title: "Trivia Facts",
    },
    {
      name: "colorToken",
      type: "string",
      title: "Personal Hex Color Token",
      initialValue: "#C0C0C0",
    },
  ],
};
